spring:
  application:
    name: spring-webflux-r2dbc-boilerplate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

management:
  endpoints:
    web:
      base-path: /mgmt
      exposure:
        include: health, metrics