spring:
  config:
    activate:
      on-profile: local
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/springdb
    username: spring
    password: spring0!
  liquibase:
    url: jdbc:postgresql://localhost:5432/springdb
    user: spring
    password: spring0!

datasource:
    host: localhost
    username: spring
    password: spring0!
    database: springdb

logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG # for queries
    io.r2dbc.postgresql.PARAM: DEBUG # for parameters